# production docker-compose

version: "3.5"
services:
  app:
    build:
      context: .
      target: aquarium
    # TODO: change to aquarium org
    image: bjkeller/aquarium:2.7.1
    command: ["production"]
    environment:
      RAILS_ENV: production
      RACK_ENV: production
    volumes:
      - public:/aquarium/public
      - logs:/aquarium/log
      - shared:/aquarium/shared

  krill:
    image: bjkeller/aquarium:2.7.1
    command: ["krill", "production"]

  web:
    volumes:
      - public:/aquarium/public
      - logs:/aquarium/log
      - shared:/aquarium/shared
      - ./docker/nginx.production.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  public:
  logs:
  shared:
