# database configuration for docker contained aquarium

default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>
  encoding: utf8
  reconnect: false
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
  pool: 100

# use the same name as production to avoid issues with switching env in docker
development:
  <<: *default
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
